name: Develop Branch CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo ${{github.ref}}
      - uses: actions/checkout@master

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12"
          check-latest: true

      - name: Install
        run: npm install

      - name: Build
        run: npm run build --if-present

      - name: Test
        run: npm test
